### PR TITLE
CMake instructions for downloading Eigen

### LINKED ISSUE #114: Remove eigen external libraries
**Is your feature request related to a problem? Please describe.**
External libraries consume space in the repository and have to be updated manually.

**Describe the solution you'd like**
Remove them from `external` folder and download them in `cmake` before building the package or whenever needed. This should be straightforward for the cases of `boost` and `eigen`. For `lpsolve` removing from external could be more complicated. 

**EDIT:** to make the procedure more clear we stick with `eigen` in this issue and we will open specified issues for the rest of the libraries

### PR DESCRIPTION
**Pull request by vaithak**
For #114

### CODE REVIEW

**Comment by vissarion** [comment]
Looks cool, thanks!

For which versions of eigen is this working? It seems that circleci tests are failing.

**Comment by TolisChal** [comment]
Nice PR, thanks!

**Comment by vaithak** [comment]
@vissarion It is working with the latest stable release of Eigen, i.e 3.3.9. 
I checked the details of CircleCI build failure, the reason is that the FetchContent module of CMake is available in version >= 3.11, and the CMake version used in CircleCI is 3.7.2. 
I have updated the CMakeLists.txt to require a minimum version of 3.11. 
Is it possible to update the CMake on CircleCI?

**Comment by vaithak** [comment]
@vissarion CircleCI test is still failing because of the CMake version, can we add instructions to build the latest version in CircleCI rather than installing it from apt-get?

**Comment by vissarion** [comment]
> @vissarion CircleCI test is still failing because of the CMake version, can we add instructions to build the latest version in CircleCI rather than installing it from apt-get?

I updated the circleci script, let's see if this fixes your problem (you have to merge with current develop). Otherwise, feel free to propose a change in the circleci script (inside this PR) that make the tests passing.

**Comment by vaithak** [comment]
> > @vissarion CircleCI test is still failing because of the CMake version, can we add instructions to build the latest version in CircleCI rather than installing it from apt-get?
> 
> I updated the circleci script, let's see if this fixes your problem (you have to merge with current develop). Otherwise, feel free to propose a change in the circleci script (inside this PR) that make the tests passing.

Yup, the circleci test is passing now, I hope this can be merged now 😅

**Review by vissarion — APPROVED** [review]

**Review by pradeexsu — COMMENTED** [review]
nice, I got an idea for lpsolve library

**Review by pradeexsu — COMMENTED** [review]
it's fine

**Pull request merged**
