### PR TITLE
CMake instructions for boost library

### LINKED ISSUE #140: Remove boost external libraries
**Is your feature request related to a problem? Please describe.**
External libraries consume space in the repository and have to be updated manually.

**Describe the solution you'd like**
Remove `boost` from `external` folder and download them in `cmake` before building the package or whenever needed. 

See how this was done for eigen https://github.com/GeomScale/volume_approximation/pull/131

### PR DESCRIPTION
**Pull request by vaithak**
For #140

### CODE REVIEW

**Comment by vaithak** [comment]
@vissarion @TolisChal, I am encountering some issues in this PR, firstly Github Actions is now using Ubuntu 20.04 which doesn't have versions less than 7.0 of g++, so I have removed them from the GitHub Actions yml file, is this ok or should we add a label for OS like "ubuntu-18.04" instead of "ubuntu-latest". 
Also, some of the tests are failing for any release of boost (not working with any stable release, tested till 1.60.0), I think we should update the tests according to the values outputted by the most recent stable release of boost.
What do you suggest?

**Comment by vissarion** [comment]
First, thanks for this PR!

> @vissarion @TolisChal, I am encountering some issues in this PR, firstly Github Actions is now using Ubuntu 20.04 which doesn't have versions less than 7.0 of g++, so I have removed them from the GitHub Actions yml file, is this ok or should we add a label for OS like "ubuntu-18.04" instead of "ubuntu-latest".

for now changing `ubuntu-latest` to `ubuntu-18.04` and keeping all `g++` versions seems the most appropriate.  Later we should add cases for `ubuntu-20.04` with `g++` version > 6.

> Also, some of the tests are failing for any release of boost (not working with any stable release, tested till 1.60.0), I think we should update the tests according to the values outputted by the most recent stable release of boost.
> What do you suggest?

Are there large divergences in the results? If not just update with the most recent stable release of boost (i.e. `1.75`)

**Comment by vaithak** [comment]
Thanks for replying,
> Are there large divergences in the results? If not just update with the most recent stable release of boost (i.e. `1.75`)

I checked the results and some are very wrong, like see [this failed test case](https://gist.github.com/vaithak/6d4a8e97e34f58725bc715cb847c3065#file-out-txt-L818), it is for volume of a 4 dimensional [-1,1] cube, the volume is wrongly computed as 24.85 which is a large divergence from the actual answer of 16.

**Comment by vissarion** [comment]
> I checked the results and some are very wrong, like see [this failed test case](https://gist.github.com/vaithak/6d4a8e97e34f58725bc715cb847c3065#file-out-txt-L818), it is for volume of a 4 dimensional [-1,1] cube, the volume is wrongly computed as 24.85 which is a large divergence from the actual answer of 16.

Ok, I see there are a lot of results completely off. Is this with boost `1.75`? Do you get the similar divergences with older releases (e.g. `1.60`) ?

**Comment by vaithak** [comment]
> Ok, I see there are a lot of results completely off. Is this with boost `1.75`? Do you get the similar divergences with older releases (e.g. `1.60`) ?

Yes, this also happens with other releases of boost (I tested with `1.75`, `1.72`, `1.70`, `1.65`, `1.60`)

**Comment by TolisChal** [comment]
Hi @vaithak and thank you very much for this PR! 
I used your modifications to test boost 1.66.0 and seems to be ok.

Maybe a few tests will be broken but with no unreasonable results. You could fix them to pass successfully.

You could also add the `Eigen.cmake` and `Boost.cmake` in root/examples too, because now the compile fails in that folder.

**Comment by vaithak** [comment]
I have made the necessary changes in expected values in the failing tests to make it work with stable releases of boost (working with 1.75) as discussed with @TolisChal. 
Also, I have added the `Boost.cmake` and `Eigen.cmake` files in the examples directory.

**Review by TolisChal — APPROVED** [review]

**Pull request merged**
