### PR TITLE
Remove directory volestipy

### LINKED ISSUE #200: Remove volestipy directory
If I am not mistaken the [`volestipy`](https://github.com/GeomScale/volesti/tree/develop/volestipy) folder
can be now removed.

### PR DESCRIPTION
**Pull request by TolisChal**
This PR removes the redundant directory of `./volestipy` due to `dingo` package.

The PR also resolves issue https://github.com/GeomScale/volesti/issues/200.

### CODE REVIEW

**Review by vissarion — APPROVED** [review]
Thanks I am OK with merging. It would be useful to state in the commit message that this is a breaking change.

**Comment by vissarion** [comment]
Also please update the main volesti README file regarding the `python` interface.

**Comment by vissarion** [comment]
`VolEsti is a C++ library for volume approximation and sampling of convex bodies (e.g. polytopes) with an R and limited python interface.` should also be rephrased. Thanks

**Comment by TolisChal** [comment]
> `VolEsti is a C++ library for volume approximation and sampling of convex bodies (e.g. polytopes) with an R and limited python interface.` should also be rephrased. Thanks

Thank you @vissarion. Please check if the readme is ok now.

**Comment by TolisChal** [comment]
This is a breaking change! Only package `dingo` could be used by Python users after this PR.

**Pull request merged**
