### PR TITLE
ZPolytopes Volume

### PR DESCRIPTION
**Pull request by bsarthak16**

### CODE REVIEW

**Review by vissarion — COMMENTED** [review]
Thanks for the effort and for opening this PR. I have a lot of things that I do not understand here... First what is a Zpolytope? Are you writing your own algorithm to estimate the volume? Please read about the mathematical background here, a good starting point is https://journal.r-project.org/archive/2021/RJ-2021-077/RJ-2021-077.pdf

**Comment by bsarthak16** [comment]
I have improved the PR please have a look on it and for more detailed information about z-polytopes and the changes i have done please check https://docs.google.com/document/d/1c6JdsPId9ujUYgDOyMPkGfhd-8KQhV5ybcKv-Txrxrg/edit?usp=sharing

**Comment by vissarion** [comment]
There is a confusion between Zpolytopes and Vpolytopes. Your example is a copy from https://github.com/GeomScale/volesti/blob/develop/examples/vpolytope-volume/vpolytopevolume.cpp

**Comment by bsarthak16** [comment]
Hi I am very sorry for what i did i used the v polytope code for help to make a program for z polytope but i accidently pasted the v-polytope code there i am again very sorry for that and i have this time made the write changes and sorry for wasting your time

**Pull request closed without merging**
