### PR TITLE
Basic c++ documentation addition

### PR DESCRIPTION
**Pull request by AlexManochis**
This PR contributes C++ documentation tools and content

### CODE REVIEW

**Review by vissarion — APPROVED** [review]
Thanks!

**Comment by elias-tsigaridas** [comment]
It looks ok to me.

**Review by elias-tsigaridas — APPROVED** [review]
It looks ok to me.

**Review by TolisChal — APPROVED** [review]

**Comment by TolisChal** [comment]
Thank you for this really useful PR! Good work!

**Pull request merged**
