### PR TITLE
Delete redundant .vscode in .gitignore

### PR DESCRIPTION
**Pull request by dymil**

### CODE REVIEW

**Comment by vissarion** [comment]
Thanks @dymil. Why is this file redundant? As far as I understand this is useful to be ignored for developers that work on visualstudio code.

**Comment by dymil** [comment]
In .gitignore, there are two of them!

**Comment by vissarion** [comment]
right, thanks!

**Comment by dymil** [comment]
It's listed twice in the file, which I presume makes one appearance
redundant.

**Pull request merged**
