### PR TITLE
Inefficient handling of burn in phase in sampling functions

### PR DESCRIPTION
**Pull request by hzratali**

### CODE REVIEW

**Review by vissarion — COMMENTED** [review]
Please do not change the code style. Apart from some rear cases (indentation mistakes) the rest are not needed. Also this makes it difficult to review the code since the reviewer cannot easily find the real changes.

**Comment by hzratali** [comment]
> Please do not change the code style. Apart from some rear cases (indentation mistakes) the rest are not needed. Also this makes it difficult to review the code since the reviewer cannot easily find the real changes.

Okay sir,
Thank you so much for the advice.

**Comment by vissarion** [comment]
@ha-rahman could you please explain the purpose of the proposed changes? Thanks.

**Comment by vissarion** [comment]
Closing it for now but please feel free to explain your intentions here.

**Pull request closed without merging**
